server:
  port: ":8080"
datasource:
  host: 127.0.0.1
  port: 3307
  database: tiktok_e-commence
  username: root
  password: "041212"
  charset: utf8mb4
jwt:
  accessTokenKey: "i love you"
  refreshTokenKey: "forever"
consul:
  addr: "127.0.0.1:8500"