server:
  port: ":8080"
datasource:
  host: 127.0.0.1
  port: 3306
  database: tiktok_e-commence
  username: root
  password: "041212"
  charset: utf8mb4
jwt:
  accessTokenKey: "i love you"
  refreshTokenKey: "forever"
consul:
  addr: "127.0.0.1:8500"
#meilisearch:
#  addr: "http://localhost:7700"
#  key: "tiktok_e-commence"